### ISSUE TITLE
Matthias hand us the expected input to robot framework

### ISSUE THREAD

**Issue by Fkar97** [IL2232-HT2022-HIL/SOFTWARE_DEV#14]
An example of how a test might look on robot framework from Matthias.

**Comment by matthiasthomasbecker** [comment]
Hi,

here is a rough sketch of what I thought a test could look like (I thought for the beginning a [keyword driven](http://robotframework.org/RobotDemo/#id5) approach could be simplest). Any suggestions from your side are also welcome.

One of the requirements for the lab could be: After a pedestrian pushes the button at a traffic light it takes up to 10 seconds until the signal turns green. 
```
[Arguments]     ${traffic_light}                                    //argument lets us select which traffic light to test
wait until ${traffic_light} pedestrian_red ON                       //'wait until' an output has a certain state, parameter 1 output name, parameter 2 
output should be ${traffic_light} pedestrian_green OFF              //'output should be' confirms  the state of a given output
push button ${traffic_light}                                        //'push button' sets and resets the button signal 
wait until led ${traffic_light}  pedestrian_green ON timeout 10000  //additional parameter with timeout [ms]
output should be ${traffic_light} pedestrian_red OFF
```

**Comment by matthiasthomasbecker** [comment]
one thing that could be important is the possibility to check multiple outputs at the same time (also wait for one and check others). Since there is some latency between issuing commands and reading the actual state of a pin, in the example above, the green led in line 3 could already be turned on if there was no traffic which would make the test wrongfully fail.
